[project]
name = "lg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "debugpy>=1.8.19",
    "python-hue-v2>=2.2.1",
    "pywebostv>=0.8.9",
    "rpi-gpio>=0.7.1",
]
